## Geometry Analysis Homework solution

In [2]:
import os
import numpy

In [8]:
file_location = os.path.join("data", "water.xyz")
xyz_file = numpy.genfromtxt(fname = file_location, dtype = "unicode", skip_header = 2)

In [9]:
print(xyz_file)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [13]:
# split data types
symbols = xyz_file[:, 0]
coordinates = xyz_file[:, 1:]
print(symbols)
print(coordinates)

['O' 'H1' 'H2']
[['0.000000' '-0.007156' '0.965491']
 ['-0.000000' '0.001486' '-0.003471']
 ['0.000000' '0.931026' '1.207929']]


In [16]:
coordinates = coordinates.astype(numpy.float)
print(coordinates)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


$$ distance = \sqrt{(x1-x2)^2 + (y1-y2)^2 + (z1-z2)^2}$$

In [18]:
num_atoms = len(symbols)
print(num_atoms)

3


In [32]:
for num1 in range(0, num_atoms):
    for num2 in range(0, num_atoms):
        #print(F"Atom 1 is {num1}")
        #print(F"Atom 2 is {num2}")
        if num1 < num2:
            x_distance = coordinates[num1, 0] - coordinates[num2, 0]  # row is num1
            y_distance = coordinates[num1, 1] - coordinates[num2, 1]
            z_distance = coordinates[num1, 2] - coordinates[num2, 2]
            distance_12 = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
            if distance_12 > 0 and distance_12 <= 1.5:
                print(F"{symbols[num1]} to {symbols[num2]} : {distance_12:.3f}")
        

O to H1 : 0.969
O to H2 : 0.969


In [33]:
import os
import numpy

file_location = os.path.join("data", "water.xyz")
xyz_file = numpy.genfromtxt(fname = file_location, dtype = "unicode", skip_header = 2)

symbols = xyz_file[:, 0]
coordinates = xyz_file[:, 1:]

coordinates = coordinates.astype(numpy.float)

num_atoms = len(symbols)

for num1 in range(0, num_atoms):
    for num2 in range(0, num_atoms):
        if num1 < num2:
            x_distance = coordinates[num1, 0] - coordinates[num2, 0]  # row is num1
            y_distance = coordinates[num1, 1] - coordinates[num2, 1]
            z_distance = coordinates[num1, 2] - coordinates[num2, 2]
            distance_12 = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
            if distance_12 > 0 and distance_12 <= 1.5:
                print(F"{symbols[num1]} to {symbols[num2]} : {distance_12:.3f}")

O to H1 : 0.969
O to H2 : 0.969
